# Generated by Django 5.2.4 on 2025-07-23 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status for this work record', max_length=20),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='user',
            field=models.ForeignKey(default=1, help_text='Business owner who recorded this work', on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
