# Generated by Django 5.2.4 on 2025-07-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(help_text='Auto-generated sale number', max_length=50),
        ),
    ]
