# Generated by Django 5.2.4 on 2025-07-23 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique identifier for the employee', max_length=20, unique=True)),
                ('employee_name', models.CharField(help_text='Full name of the employee', max_length=100)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', help_text='Whether the employee is full-time or part-time', max_length=10)),
                ('pay', models.DecimalField(decimal_places=2, help_text='Employee pay rate (per hour for part-time, monthly/annual for full-time)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the employee is currently active')),
                ('date_hired', models.DateField(auto_now_add=True, help_text='Date when the employee was hired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['employee_name'],
            },
        ),
    ]
