# Generated by Django 5.2.4 on 2025-07-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_subcategory',
            field=models.CharField(blank=True, help_text='Specific subcategory of your business type', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(choices=[('food_beverage', 'Food & Beverage'), ('retail', 'Retail'), ('beauty', 'Beauty'), ('health_wellness', 'Health & Wellness'), ('services', 'Services')], help_text='Type of business you operate', max_length=20),
        ),
    ]
